### ISSUE TITLE
4+1 Content 

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Economics#1]
Please do not edit or remove any of the new 4+1 content. These are brand new revisions written by the chair Mike Leeds and the program is not on the bulletin yet to link to so the description, deadlines and application instructions need to be stated as they are.

**Comment by tu-chill** [comment]
@saracurnow and @CVE82 What is the status of this issue? can we close it?

**Comment by saracurnow** [comment]
Yes, I will close it now. I'm not working on econ yet but I know not to change any of the 4+1 content for any department (unless there's a typo, &c).
