### ISSUE TITLE
Can we saturate/darken the hero image?

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Economics#3]
Hey Zac can we saturate/darken the hero image just a bit so the white text stands out some? Thanks!

**Comment by ZMcGroarty** [comment]
Hows this?

![department-of-economics-temple2](https://user-images.githubusercontent.com/15017242/35878062-26045db6-0b45-11e8-884a-9b948af666e0.png)

**Comment by CVE82** [comment]
That is BOMB thank you!!!
